// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreditsController from "./credits_controller"
application.register("credits", CreditsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProjectThumbnailController from "./project_thumbnail_controller"
application.register("project-thumbnail", ProjectThumbnailController)
